//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpOneApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class helponeEntities : DbContext
    {
        public helponeEntities()
            : base("name=helponeEntities")
        {
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adm> adm { get; set; }
        public virtual DbSet<comentarios> comentarios { get; set; }
        public virtual DbSet<conexao> conexao { get; set; }
        public virtual DbSet<conversas> conversas { get; set; }
        public virtual DbSet<convite_conexao> convite_conexao { get; set; }
        public virtual DbSet<materias> materias { get; set; }
        public virtual DbSet<mensagens> mensagens { get; set; }
        public virtual DbSet<perfil> perfil { get; set; }
        public virtual DbSet<topico> topico { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<usuario_dificuldades> usuario_dificuldades { get; set; }
        public virtual DbSet<usuario_facilidades> usuario_facilidades { get; set; }
    }
}
