//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpOneApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfil
    {
        public int id_perfil { get; set; }
        public Nullable<int> id_materia_interesse { get; set; }
        public Nullable<int> id_materia_disposicao { get; set; }
        public string tx_como_conheceu { get; set; }
        public Nullable<int> id_usuario { get; set; }
    
        public virtual materias materias { get; set; }
        public virtual materias materias1 { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
