//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpOneApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_facilidades
    {
        public int id_usuario_facilidade { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_materia { get; set; }
    
        public virtual materias materias { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
