//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpOneApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int u_id { get; set; }
        public string u_nome { get; set; }
        public Nullable<System.DateTime> u_data_nasc { get; set; }
        public string u_sexo { get; set; }
        public string u_email { get; set; }
        public string u_cpf { get; set; }
        public string u_login { get; set; }
        public string u_senha { get; set; }
        public string u_cidade { get; set; }
        public string u_estado { get; set; }
    }
}
